DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	ID			SERIAL			PRIMARY KEY,
	USERNAME	VARCHAR(255)	NOT NULL	UNIQUE,
	ROLE		VARCHAR(255)	NOT NULL	UNIQUE,
	PASSWORD	VARCHAR(255)	NOT NULL
);

INSERT INTO USERS (USERNAME, ROLE, PASSWORD) VALUES ('admin', 'ADMIN', '$2a$04$0PO3VCOloAjnoxSj8Ff1muWfLLa0PfPPvS/4Bh4V0qQ2UkOrHSHOq'); --Pass: 123
INSERT INTO USERS (USERNAME, ROLE, PASSWORD) VALUES ('user', 'USER', '$2a$04$L3BMwyds/ELxW6LDpqt21eXxV5E50Y3SwaCRcd5Q7gxtkXRI4rsnC');  --Pass: 456

SELECT * FROM USERS;